### ISSUE TITLE
yarn test issue on win 10

### ISSUE THREAD

**Issue by ilazarte** [bitjson/typescript-starter#18] opened 2017-03-17 00:24 UTC
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Trying to following initial setup here.
yarn install - works great.
yarn watch - gets stuck towards the end on what sort of looks like bad argument passing (see attached stacktrace)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

$ yarn watch
yarn watch v0.21.3
$ yarn build && yarn build:tests -- --no-browser && concurrently -r --kill-others 'npm run --silent build:main -- -w' 'npm run --silent build:tests -- -w --no-browser' 'sleepms 2000 && ava --watch'
yarn build v0.21.3
$ trash build && yarn build:main && yarn build:module && yarn build:browser-deps && yarn build:browser && yarn build:browser-cjs && yarn build:resolve-sourcemaps
yarn build:main v0.21.3
$ tsc -p tsconfig.json
Done in 1.22s.
yarn build:module v0.21.3
$ tsc -p config/exports/tsconfig.module.json
Done in 1.29s.
yarn build:browser-deps v0.21.3
$ mkdirp build/temp && browserify node_modules/hash.js/lib/hash.js --standalone hash -o build/temp/hash.js
Done in 0.66s.
yarn build:browser v0.21.3
$ rollup -c config/exports/rollup.config.js -f es -o build/browser/index.js
Done in 0.68s.
yarn build:browser-cjs v0.21.3
$ rollup -c config/exports/rollup.config.js -f cjs -o build/browser/index.cjs.js
Done in 0.67s.
yarn build:resolve-sourcemaps v0.21.3
$ sorcery -i build/browser/index.js && sorcery -i build/browser/index.cjs.js
Done in 0.53s.
Done in 7.07s.
yarn build:tests v0.21.3
$ trash test && node config/exports/build-tests.js --no-browser
Done in 0.73s.
'np' is not recognized as an internal or external command,
operable program or batch file.
'run' is not recognized as an internal or external command,
operable program or batch file.
'-w'' is not recognized as an internal or external command,
operable program or batch file.
'np' is not recognized as an internal or external command,
operable program or batch file.
'run' is not recognized as an internal or external command,
operable program or batch file.
'--silent' is not recognized as an internal or external command,
operable program or batch file.
The filename, directory name, or volume label syntax is incorrect.
'-w' is not recognized as an internal or external command,
operable program or batch file.
'--no-browser'' is not recognized as an internal or external command,
operable program or batch file.
'sleepm' is not recognized as an internal or external command,
operable program or batch file.
'2000' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

**Comment by dngsdk** [comment] 2017-03-19 22:06
I can confirm the issue.

**Comment by ilazarte** [comment] 2017-03-20 00:56
Closer!  I got the stack trace at the bottom on the trash test step.  Outputting the build\test directory at this point is:
C:\USERS\ILAZARTE\SRC\GITHUB\TYPESCRIPT-STARTER-LEARN\BUILD   
├───browser                                                   
│       index.cjs.js                                          
│       index.cjs.js.map                                      
│       index.js                                              
│       index.js.map                                          
│                                                             
├───main                                                      
│   │   index.d.ts                                            
│   │   index.js                                              
│   │                                                         
│   ├───adapters                                              
│   │       crypto.browser.d.ts                               
│   │       crypto.browser.js                                 
│   │                                                         
│   └───lib                                                   
│           async.d.ts                                        
│           async.js                                          
│           async.spec.d.ts                                   
│           async.spec.js                                     
│           hash.d.ts                                         
│           hash.js                                           
│           hash.spec.d.ts                                    
│           hash.spec.js                                      
│           number.d.ts                                       
│           number.js                                         
│           number.spec.d.ts                                  
│           number.spec.js                                    
│                                                             
├───module                                                    
│   │   index.js                                              
│   │                                                         
│   ├───adapters                                              
│   │       crypto.browser.js                                 
│   │                                                         
│   └───lib                                                   
│           async.js                                          
│           async.spec.js                                     
│           hash.js                                           
│           hash.spec.js                                      
│           number.js                                         
│           number.spec.js                                    
│                                                             
└───temp                                                      
        hash.js                                               


----------------------

$ trash test && node config/exports/build-tests.js --no-browser
Done in 0.78s.
8:53:20 PM - Compilation complete. Watching for file changes.


module.js:327
    throw err;
    ^

Error: Cannot find module 'build/main/index.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ilazarte\src\github\typescript-starter-learn\src\lib\async.spec.ts:2:1)
    at Module._compile (module.js:409:26)
    at extensions.(anonymous function) (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\require-precompiled\index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\ava\lib\process-adapter.js:105:4)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\ava\lib\test-worker.js:33:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
module.js:327
    throw err;
    ^

Error: Cannot find module 'build/main/index.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ilazarte\src\github\typescript-starter-learn\src\lib\hash.spec.ts:2:1)
    at Module._compile (module.js:409:26)
    at extensions.(anonymous function) (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\require-precompiled\index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\ava\lib\process-adapter.js:105:4)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\ava\lib\test-worker.js:33:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
module.js:327
    throw err;
    ^

Error: Cannot find module 'build/main/index.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ilazarte\src\github\typescript-starter-learn\src\lib\number.spec.ts:2:1)
    at Module._compile (module.js:409:26)
    at extensions.(anonymous function) (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\require-precompiled\index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\ava\lib\process-adapter.js:105:4)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ilazarte\src\github\typescript-starter-learn\node_modules\ava\lib\test-worker.js:33:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

  3 exceptions

  × test\main\lib\async.spec.js exited with a non-zero exit code: 1

  × test\main\lib\hash.spec.js exited with a non-zero exit code: 1

  × test\main\lib\number.spec.js exited with a non-zero exit code: 1

**Comment by bitjson** [comment] 2017-04-06 02:45
Hey @ilazarte and @dngsdk – thanks for sharing! @ilazarte, were you able to get this working?

Is there an issue with Windows 10 accepting strings in single quotes? (I don't have a great way of testing on Windows.)

I'd love to merge a pull request if one of you is willing to create it!

**Comment by Markosyan-AR** [comment] 2017-07-05 05:45
I've replaced quotes, but it didn't helps

PS D:\DEV\JS\Typescript-hyped> yarn watch
yarn watch v0.27.5
$ yarn build && yarn build:tests -- --no-browser && concurrently -r --kill-others "npm run --silent build:main -- -w" "npm run --silent build:tests -- -w --no-browser" "sleepms 2000 && ava --watch"
Error: Command failed: D:\DEV\JS\Typescript-hyped\node_modules\trash\lib\win-trash.exe D:\DEV\JS\Typescript-hyped\build

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
error Command failed with exit code 1.
error Command failed with exit code 1.

**Comment by 6matko** [comment] 2017-07-08 18:40
Unfortunately, I have the same issue as @ilazarte and also on Win10. I am experiencing absolutely the same behavior and the same error traces.

**Comment by mitch-b** [comment] 2017-09-26 15:17
Sorry for the "me too" comment, but since this issue has been silent for a while -- does anyone have ideas on where to look? I'm willing to put time into it, but I'm completely new to most of these tools. Is this an issue in `nyc` or `ava`? I noticed running the following produces the same problem:

```
# mimicing call "nyc ava"

PS> node .\node_modules\nyc\bin\nyc.js .\node_modules\ava\cli.js
module.js:529
    throw err;
    ^

Error: Cannot find module 'build/browser/index.cjs.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
```

**Comment by mitch-b** [comment] 2017-09-26 18:14
Turns out, it was a lot less nuanced than I originally guessed. Boiled down to a file path issue between using `/` and `\` separators. Hopefully PR #47 works for everyone!

**Comment by hiteshdua1** [comment] 2018-01-22 10:25
HI, Still facing this issue, Any update on this ?

**Comment by mitch-b** [comment] 2018-01-22 13:42
@hiteshdua1 - can you try using changes offered in PR by asmagin? 

https://github.com/bitjson/typescript-starter/pull/48/files

**Comment by hiteshdua1** [comment] 2018-01-23 05:52
There were some errors initially , so I ran 
`yarn reset`

then i updated the code as per pull request and It worked fine after that

**Comment by bitjson** [comment] 2018-03-10 19:04
Fixed in https://github.com/bitjson/typescript-starter/pull/48. Thanks @asmagin!

**Closed by bitjson** 2018-03-10 19:04 UTC
Labels: bug, help wanted
